# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '母板.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import pygame
import os
from PIL import Image, ImageQt
from PyQt5.QtGui import QPixmap,QImage
from PyQt5.QtWidgets import QWidget, QApplication, QVBoxLayout, QLabel

"""
99  999999   999999  99    99   9999   99    99
99 99999999 99999999 99    99  99  99  99    99
99  999999999999999  99    99 99    99 99    99
99    999999999999     9999   99    99 99    99
99      99999999        99    99    99 99    99
99        9999          99     99  99  99    99
99         99           99      9999    999999 
"""
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 480)
        Form.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.center = QtWidgets.QFrame(Form)
        self.center.setGeometry(QtCore.QRect(2, 80, 791, 248))
        self.center.setStyleSheet("QWidget#center{\n"
"\n"
"border: 1px solid rgb(106, 106, 106);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center.setObjectName("center")
        self.layoutWidget = QtWidgets.QWidget(self.center)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 40, 671, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.test = QtWidgets.QFrame(self.layoutWidget)
        self.test.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.test.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test.setObjectName("test")
        self.label_3 = QtWidgets.QLabel(self.test)
        self.label_3.setGeometry(QtCore.QRect(0, 133, 121, 22))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.test)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 121, 121))
        self.label_4.setStyleSheet("border-style: solid; border-width: 1px; border-radius: 10px; border-color: blue;")
        self.label_4.setText("")
        pygame.init()
        img1 = pygame.image.load("../img/test.png")
        pix = self.surface2pixmap(img1)
        self.label_4.setPixmap(pix)
        # self.label_4.setScaledContents(True)

        # self.label_4.setPixmap(QtGui.QPixmap("../img/test.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.test)
        self.batch = QtWidgets.QFrame(self.layoutWidget)
        self.batch.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.batch.setFrameShadow(QtWidgets.QFrame.Raised)
        self.batch.setObjectName("batch")
        self.label_23 = QtWidgets.QLabel(self.batch)
        self.label_23.setGeometry(QtCore.QRect(0, 133, 121, 22))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.batch)
        self.label_24.setGeometry(QtCore.QRect(0, 0, 121, 121))
        self.label_24.setStyleSheet("border-style: solid; border-width: 1px; border-radius: 10px; border-color: blue;")
        self.label_24.setText("")
        pygame.init()
        img1 = pygame.image.load("../img/batch.png")
        pix = self.surface2pixmap(img1)
        self.label_24.setPixmap(pix)
        # self.label_24.setScaledContents(True)

        # self.label_24.setPixmap(QtGui.QPixmap("../img/batch.png"))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.batch)
        self.history = QtWidgets.QFrame(self.layoutWidget)
        self.history.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.history.setFrameShadow(QtWidgets.QFrame.Raised)
        self.history.setObjectName("history")
        self.label_19 = QtWidgets.QLabel(self.history)
        self.label_19.setGeometry(QtCore.QRect(0, 133, 121, 22))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.history)
        self.label_20.setGeometry(QtCore.QRect(0, 0, 121, 121))
        self.label_20.setStyleSheet("border-style: solid; border-width: 1px; border-radius: 10px; border-color: blue;")
        self.label_20.setText("")
        pygame.init()
        img1 = pygame.image.load("../img/history.png")
        pix = self.surface2pixmap(img1)
        self.label_20.setPixmap(pix)
        # self.label_20.setScaledContents(True)

        # self.label_20.setPixmap(QtGui.QPixmap("../img/history.png"))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.history)
        self.project = QtWidgets.QFrame(self.layoutWidget)
        self.project.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.project.setFrameShadow(QtWidgets.QFrame.Raised)
        self.project.setObjectName("project")
        self.label_9 = QtWidgets.QLabel(self.project)
        self.label_9.setGeometry(QtCore.QRect(0, 133, 121, 22))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.project)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 121, 121))
        self.label_10.setStyleSheet("border-style: solid; border-width: 1px; border-radius: 10px; border-color: blue;")
        self.label_10.setText("")
        pygame.init()
        img1 = pygame.image.load("../img/project.png")
        pix = self.surface2pixmap(img1)
        self.label_10.setPixmap(pix)
        # self.label_10.setScaledContents(True)

        # self.label_10.setPixmap(QtGui.QPixmap("../img/project.png"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.project)
        self.setup = QtWidgets.QFrame(self.layoutWidget)
        self.setup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setup.setObjectName("setup")
        self.label_16 = QtWidgets.QLabel(self.setup)
        self.label_16.setGeometry(QtCore.QRect(0, 133, 121, 22))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.setup)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 121, 121))
        self.label_17.setStyleSheet("border-style: solid; border-width: 1px; border-radius: 10px; border-color: blue;")
        self.label_17.setText("")
        pygame.init()
        img1 = pygame.image.load("../img/setup.png")
        pix = self.surface2pixmap(img1)
        self.label_17.setPixmap(pix)
        # self.label_17.setScaledContents(True)

        # self.label_17.setPixmap(QtGui.QPixmap("../img/setup.png"))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.setup)
        self.under = QtWidgets.QFrame(Form)
        self.under.setGeometry(QtCore.QRect(0, 435, 800, 45))
        self.under.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.under.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.under.setFrameShadow(QtWidgets.QFrame.Raised)
        self.under.setObjectName("under")
        self.label_13 = QtWidgets.QLabel(self.under)
        self.label_13.setGeometry(QtCore.QRect(360, 0, 80, 45))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_13.setObjectName("label_13")
        self.dateLabel = QtWidgets.QLabel(self.under)
        self.dateLabel.setGeometry(QtCore.QRect(0, 0, 130, 45))
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.timeLabel = QtWidgets.QLabel(self.under)
        self.timeLabel.setGeometry(QtCore.QRect(680, 0, 120, 45))
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setGeometry(QtCore.QRect(0, 330, 800, 101))
        self.frame_6.setStyleSheet("QWidget#frame_6{\n"
"\n"
"border: 1px solid rgb(106, 106, 106);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.shutdown = QtWidgets.QFrame(self.frame_6)
        self.shutdown.setGeometry(QtCore.QRect(707, 3, 60, 81))
        self.shutdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shutdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shutdown.setObjectName("shutdown")
        self.label_12 = QtWidgets.QLabel(self.shutdown)
        self.label_12.setGeometry(QtCore.QRect(0, 62, 60, 18))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_18 = QtWidgets.QLabel(self.shutdown)
        self.label_18.setGeometry(QtCore.QRect(0, 1, 60, 60))
        self.label_18.setText("")
        pygame.init()
        img1 = pygame.image.load("../img/shutdown.png")
        pix = self.surface2pixmap(img1)
        self.label_18.setPixmap(pix)
        # self.label_18.setScaledContents(True)

        # self.label_18.setPixmap(QtGui.QPixmap("../img/shutdown.png"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.top = QtWidgets.QFrame(Form)
        self.top.setGeometry(QtCore.QRect(2, 1, 791, 80))
        self.top.setStyleSheet("QWidget#top{\n"
"\n"
"border: 1px solid rgb(106, 106, 106);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.label = QtWidgets.QLabel(self.top)
        self.label.setGeometry(QtCore.QRect(209, 2, 381, 72))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.home = QtWidgets.QFrame(self.top)
        self.home.setGeometry(QtCore.QRect(718, 2, 70, 75))
        self.home.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home.setObjectName("home")
        self.label_11 = QtWidgets.QLabel(self.home)
        self.label_11.setGeometry(QtCore.QRect(2, 0, 55, 55))
        self.label_11.setText("")

        img1 = pygame.image.load("../img/batch.png")
        pix = self.surface2pixmap(img1)
        self.label_11.setPixmap(pix)
        # self.label_24.setScaledContents(True)

        # self.label_24.setPixmap(QtGui.QPixmap("../img/batch.png"))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_2 = QtWidgets.QLabel(self.home)
        self.label_2.setGeometry(QtCore.QRect(0, 56, 62, 15))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.frame_6.raise_()
        self.center.raise_()
        self.under.raise_()
        self.top.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "测试"))
        self.label_23.setText(_translate("Form", "批量测试"))
        self.label_19.setText(_translate("Form", "历史"))
        self.label_9.setText(_translate("Form", "项目"))
        self.label_16.setText(_translate("Form", "设置"))
        self.label_13.setText(_translate("Form", "主菜单"))
        self.dateLabel.setText(_translate("Form", "TextLabel"))
        self.timeLabel.setText(_translate("Form", "TextLabel"))
        self.label_12.setText(_translate("Form", "关机"))
        self.label.setText(_translate("Form", "胶体金检测分析仪"))
        self.label_2.setText(_translate("Form", "测试"))

    # 图片处理
    def surface2pixmap(self, pygame_surface):
        # 将 Pygame Surface 转换为 QImage
        image = QImage(pygame.image.tostring(pygame_surface, 'RGBA'),
                       pygame_surface.get_width(),
                       pygame_surface.get_height(),
                       QImage.Format_RGBA8888)  # 使用 RGBA 格式

        # 将 QImage 转换为 QPixmap
        return QPixmap(image)
